---
new_page_extension: md
auto_deploy: false
admin_path: "/dist"
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: content/data/home.json
  label: Home Page
- type: document
  path: content/data/company.json
  label: Company Info
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
